WIP: Make function not access outer-state
spotify/flyte-flink-plugin pull request #265
Opened 2023-02-06 17:36 UTC by live-wire

- Minor refactor to use functionality upstream

2023-02-08 08:19 UTC, regadas requested changes

2023-02-08 08:19 UTC, regadas commented on pkg/flink/handler.go
> +func FlinkClusterTaskLogs(ctx context.Context, flinkTaskLogs FlinkTaskLogs) ([]*core.TaskLog, error) {
Let's have `*Config` as an argument, and could `FlinkTaskLogsInput` be a better name? similar to `tasklog.Input`?

2023-02-11 01:44 UTC, live-wire commented
@regadas made the suggested changes 👍 
Please have a look

2023-02-11 07:41 UTC, regadas commented on pkg/flink/handler.go
> +func FlinkClusterTaskLogs(ctx context.Context, fi FlinkTaskLogsInput, config *Config) ([]*core.TaskLog, error) {
```suggestion
func FlinkClusterTaskLogs(ctx context.Context, config *Config, fi FlinkTaskLogsInput) ([]*core.TaskLog, error) {
```

2023-02-11 07:42 UTC, regadas commented on pkg/flink/handler.go
> +	}, GetFlinkConfig())
```suggestion
	tl, err := FlinkClusterTaskLogs(ctx, GetFlinkConfig(), FlinkTaskLogsInput{
		ClusterName: flinkCluster.Name,
		Namespace:   flinkCluster.Namespace,
	})
```

2023-02-11 07:48 UTC, regadas approved these changes
🚀

2023-02-11 07:48 UTC, regadas commented on pkg/flink/handler.go
> +	}, GetFlinkConfig())
:art: I did a minor param reorder here.

2023-02-11 07:48 UTC, merged