Add worker config
spotify/flyte-flink-plugin pull request #323
Opened 2023-10-26 18:54 UTC by smikloska

2023-10-27 17:08 UTC, regadas requested changes
Hm, this change seems a bit disconnected from this plugin, are you planning to had TShirt size logic support as well in the plugin it self?

At first, it appears that this is being added to proto but leveraged somewhere else is that correct? I would really prefer that whatever is added to be leveraged by the plugin as well.

2023-12-21 10:44 UTC, live-wire commented
> At first, it appears that this is being added to proto but leveraged somewhere else, is that correct?
Yes. It is used by a closed source plugin that depends on this plugin

> I would really prefer that whatever is added to be leveraged by the plugin as well.
Should we make use of it for worker sizing to make the PR more complete? 🤔

2023-12-21 14:41 UTC, regadas commented
> Should we make use of it for worker sizing to make the PR more complete?
@live-wire let me think about this for a little bit. We can also sync at some point IRL (maybe first week of jan?)

2025-01-29 17:47 UTC, regadas reviewed
Closing

2025-01-29 17:47 UTC, closed without merging